import { buildOccurrences, getDaySummary, toDateKey } from './task-domain.js';
import { getDailyUsageSummary, getIpadDayStatus } from './ipad-domain.js';
import { createSupabaseStore } from './supabase-store.js';

const store = createSupabaseStore();
const today = toDateKey(new Date());
const state = { memberId: '', selectedDate: today, month: today.slice(0, 7) };
const $ = (selector) => document.querySelector(selector);
const escape = (text) => String(text).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const dateLabel = (date) => new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date(`${date}T00:00:00`));
const encouragements = ['完成得漂亮，给今天的自己一个赞！', '又推进了一步，真棒。', '小事做好，生活就会闪闪发光。', '打卡成功！继续保持这个节奏。'];
const motivations = [['今天的努力，是明天的底气。', '完成一件小事，也是在认真生活。'], ['慢慢来，比较快。', '把注意力放在眼前最重要的一件事。'], ['自律不是束缚，是自由的起点。', '为想要的生活留出一点行动。'], ['做自己的光，不必等待炬火。', '你的每一次坚持都有意义。'], ['不慌不忙，按自己的节奏前行。', '今天也值得好好投入。'], ['生活由许多小完成组成。', '勾掉一项，就离轻松更近一点。'], ['保持热爱，奔赴山海。', '日常里也藏着闪亮的答案。'], ['向前走，哪怕只是一步。', '微小进步同样值得庆祝。'], ['你比昨天的自己更勇敢。', '把今天过好，就是很大的成就。'], ['所有美好，都在悄悄发生。', '给自己一点耐心和相信。'], ['认真生活的人，自带光芒。', '从完成手上的小事开始。'], ['不必完美，先完成再说。', '行动会帮你驱散犹豫。'], ['每一个清晨，都是新的开始。', '今天有新的可能等着你。'], ['日子滚烫，前行有光。', '愿你在日常中收获笃定。']];
let toastTimer; let pendingDeletion; let pendingCompletion; let pendingUndoCompletion; let motivationIndex = 0; let editingTaskId = null; let editingMemberAvatarId = null; let familyManagementRequested = false; let passwordVerified = false;
function monthBounds(month) { const end = new Date(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0); return [`${month}-01`, toDateKey(end)]; }
function selectedMember(data) { return data.members.find((member) => member.id === state.memberId); }
function memberTasks(data) { return data.tasks.filter((task) => task.memberIds.includes(state.memberId)); }
function avatarMarkup(member, className) { return member.avatar ? `<img class="${className}" src="${escape(member.avatar)}" alt="${escape(member.name)}的头像">` : `<i class="${className}" style="background:${member.color}">${escape(member.name.trim().slice(0, 1))}</i>`; }
function fileToDataUrl(file) { if (!file?.size) return Promise.resolve(''); return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function showToast(message) { $('#toast').textContent = message || encouragements[Math.floor(Math.random() * encouragements.length)]; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 2800); }
function renderMotivation() { const start = new Date(new Date().getFullYear(), 0, 0); motivationIndex = Math.floor((new Date() - start) / 86_400_000) % motivations.length; $('#motivation-text').textContent = motivations[motivationIndex][0]; $('#motivation-note').textContent = motivations[motivationIndex][1]; }
function rotateMotivation() { motivationIndex = (motivationIndex + 1) % motivations.length; const text = $('#motivation-text'); const note = $('#motivation-note'); text.classList.remove('motivation-scroll'); note.classList.remove('motivation-scroll'); void text.offsetWidth; text.textContent = motivations[motivationIndex][0]; note.textContent = motivations[motivationIndex][1]; text.classList.add('motivation-scroll'); note.classList.add('motivation-scroll'); }

function render() {
  const data = store.getState(); if (!state.memberId && data.members.length) state.memberId = data.members[0].id;
  const member = selectedMember(data); const tasks = memberTasks(data); const [monthStart, monthEnd] = monthBounds(state.month); const allMonth = buildOccurrences(tasks, monthStart, monthEnd); const selected = buildOccurrences(tasks, state.selectedDate, state.selectedDate);
  $('#member-name').textContent = member?.name || '成员'; $('#member-avatar').innerHTML = member?.avatar ? `<img src="${escape(member.avatar)}" alt="${escape(member.name)}的头像">` : (member?.name || '家').trim().slice(0, 1); $('#member-avatar').style.background = member?.avatar ? 'transparent' : (member?.color || '#6750a4');
  $('#today-label').textContent = dateLabel(state.selectedDate); $('#task-count').textContent = `${selected.length} 项任务`; $('#task-list').innerHTML = selected.length ? selected.map((item) => taskCard(item, data, false)).join('') : '<div class="empty">今天没有任务，享受一点留白吧。</div>';
  $('#task-owner-label').textContent = member ? `任务将归属给 ${member.name}` : ''; $('#task-type').innerHTML = data.types.map((type) => `<option value="${type.id}">${escape(type.name)}</option>`).join(''); $('#task-weekdays').innerHTML = ['周一','周二','周三','周四','周五','周六','周日'].map((day, index) => `<label class="check"><input type="checkbox" value="${index}"> ${day}</label>`).join('');
  $('#member-list').innerHTML = managerRows(data.members, 'member'); $('#type-list').innerHTML = managerRows(data.types, 'type'); $('#managed-task-list').innerHTML = tasks.length ? tasks.map((task) => managedTaskRow(task, data)).join('') : '<div class="empty">还没有可管理的任务。</div>'; $('#member-gate-list').innerHTML = data.members.map((item) => `<button class="member-choice" data-member-choice="${item.id}">${avatarMarkup(item, 'member-choice-avatar')}<span>${escape(item.name)}</span></button>`).join(''); $('#member-switch-list').innerHTML = data.members.map((item) => `<button class="member-switch-choice ${item.id === state.memberId ? 'active' : ''}" data-member-switch="${item.id}">${avatarMarkup(item, 'member-choice-avatar')}<span>${escape(item.name)}</span>${item.id === state.memberId ? '<b>当前</b>' : ''}</button>`).join(''); $('#open-member-switch').hidden = !(data.members.length > 1); $('#family-invite-code').textContent = store.getInviteCode?.() || '同步中'; $('#open-join-family').hidden = store.hasJoinedHousehold?.() || data.members.length > 0; renderCalendar(allMonth); renderMotivation();
}
function taskCard({ task, date, completed }, data) { const type = data.types.find((item) => item.id === task.typeId); const detail = task.completionDetails?.[date]; return `<article class="task ${completed ? 'done' : ''}"><button class="complete" data-complete="${task.id}" data-date="${date}" aria-label="${completed ? '撤销完成' : '标记完成'}">${completed ? '✓' : ''}</button><div class="task-copy" data-task-detail="${task.id}" data-date="${date}" role="button" tabindex="0"><div class="task-title">${escape(task.title)}</div>${task.description ? `<p>${escape(task.description)}</p>` : ''}<div class="meta"><span style="--tag:${type?.color || '#888'}">${escape(type?.name || '未分类')}</span><span>${task.recurrence === 'daily' ? '每天' : task.recurrence === 'weekly' ? '每周' : date}</span></div>${completed && (detail?.note || detail?.image) ? `<div class="completion-proof">${detail.image ? `<img src="${escape(detail.image)}" alt="完成照片">` : ''}${detail.note ? `<span>${escape(detail.note)}</span>` : ''}</div>` : ''}</div></article>`; }
function managedTaskRow(task, data) { const type = data.types.find((item) => item.id === task.typeId); const schedule = task.recurrence === 'daily' ? '每天' : task.recurrence === 'weekly' ? '每周' : task.startDate; return `<article class="manage-task"><i class="manage-task-mark" style="--task-color:${type?.color || '#8a7c90'}"></i><div class="manage-task-copy"><strong>${escape(task.title)}</strong><span><b style="--tag:${type?.color || '#888'}">${escape(type?.name || '未分类')}</b><em>${schedule}</em></span></div><div class="manage-task-actions"><button class="mini" data-edit="${task.id}">编辑</button><button class="mini danger" data-delete="${task.id}" data-date="${today}">删除</button></div></article>`; }
function managerRows(items, kind) { return items.map((item) => `<div class="manage-row">${kind === 'member' ? avatarMarkup(item, 'manage-member-avatar') : `<span class="color-dot" style="background:${item.color}"></span>`}<strong>${escape(item.name)}</strong><div>${kind === 'member' ? `<button class="mini" data-edit-avatar="${item.id}">头像</button>` : ''}<button class="mini" data-rename-${kind}="${item.id}">修改</button><button class="mini danger" data-delete-${kind}="${item.id}">删除</button></div></div>`).join(''); }
function renderCalendar(occurrences) { const first = new Date(`${state.month}-01T00:00:00`); const offset = (first.getDay() + 6) % 7; const last = new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: offset }, () => '<div></div>'); for (let day = 1; day <= last; day += 1) { const date = `${state.month}-${String(day).padStart(2, '0')}`; const summary = getDaySummary(occurrences, date); const status = !summary.total ? '<small class="calendar-status idle">—</small>' : date > today || (date === today && summary.completed !== summary.total) ? '<small class="calendar-status has-task" aria-label="当天有任务">—</small>' : summary.completed === summary.total ? '<small class="calendar-status complete" aria-label="任务全部完成">✓</small>' : '<small class="calendar-status pending" aria-label="任务未全部完成">✕</small>'; cells.push(`<button class="day ${date === state.selectedDate ? 'selected' : ''} ${date === today ? 'today' : ''}" data-day="${date}"><b>${day}</b>${status}</button>`); } $('#calendar-title').textContent = new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: 'long' }).format(first); $('#calendar-grid').innerHTML = cells.join(''); }
function openManage(show) { if (show) { $('#task-date').value = state.selectedDate; $('#manage-view').showModal(); } else $('#manage-view').close(); }
function chooseMember(id) { state.memberId = id; $('#member-gate').close(); $('#home-view').hidden = false; render(); }
function manageAction(event, kind) { const button = event.target.closest('button'); if (!button) return; const suffix = `${kind[0].toUpperCase()}${kind.slice(1)}`; const renameId = button.dataset[`rename${suffix}`]; const deleteId = button.dataset[`delete${suffix}`]; if (button.dataset.editAvatar) { const member = store.getState().members.find((item) => item.id === button.dataset.editAvatar); editingMemberAvatarId = member.id; $('#member-avatar-form').reset(); $('#member-avatar-preview').src = member.avatar || ''; $('#member-avatar-preview').hidden = !member.avatar; $('#member-avatar-dialog').showModal(); return; } if (renameId) { const item = store.getState()[`${kind}s`].find((value) => value.id === renameId); const name = prompt(`修改${kind === 'member' ? '成员' : '类型'}名称`, item.name)?.trim(); if (name) store[`rename${suffix}`](renameId, name); } if (deleteId && confirm(`确定删除这个${kind === 'member' ? '成员' : '类型'}吗？`)) store[`delete${suffix}`](deleteId); }
function openTaskDetail(id, date) { const data = store.getState(); const task = data.tasks.find((item) => item.id === id); if (!task) return; const type = data.types.find((item) => item.id === task.typeId); const detail = task.completionDetails?.[date]; const completed = task.completedDates.includes(date); $('#task-detail-status').textContent = completed ? 'COMPLETED' : 'TASK DETAIL'; $('#task-detail-title').textContent = task.title; $('#task-detail-meta').textContent = `${dateLabel(date)} · ${type?.name || '未分类'} · ${task.recurrence === 'daily' ? '每天' : task.recurrence === 'weekly' ? '每周' : '单次任务'}`; $('#task-detail-description').textContent = task.description || ''; $('#task-detail-description').hidden = !task.description; $('#task-detail-completion').hidden = !completed; $('#task-detail-note').textContent = detail?.note || ''; $('#task-detail-note').hidden = !detail?.note; $('#task-detail-image').src = detail?.image || ''; $('#task-detail-image').hidden = !detail?.image; $('#task-detail-dialog').showModal(); }

$('#task-form').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const title = form.get('title').trim(); if (!title) return; const weekdays = [...document.querySelectorAll('#task-weekdays input:checked')].map((input) => Number(input.value)); const taskData = { title, description: form.get('description').trim(), typeId: form.get('typeId'), startDate: form.get('date'), recurrence: form.get('recurrence'), weekdays }; if (editingTaskId) store.updateTask(editingTaskId, taskData); else store.addTaskForMember(taskData, state.memberId); editingTaskId = null; event.currentTarget.reset(); $('#task-date').value = state.selectedDate; $('#weekday-field').hidden = true; $('#task-dialog').close(); showToast('任务已保存。'); });
$('#task-list').addEventListener('click', (event) => { const button = event.target.closest('.complete'); if (button) { const task = store.getState().tasks.find((item) => item.id === button.dataset.complete); if (task.completedDates.includes(button.dataset.date)) { pendingUndoCompletion = { id: button.dataset.complete, date: button.dataset.date }; $('#undo-completion-dialog').showModal(); return; } pendingCompletion = { id: button.dataset.complete, date: button.dataset.date }; $('#completion-form').reset(); $('#completion-image-preview').hidden = true; $('#completion-image-preview').removeAttribute('src'); $('#completion-dialog').showModal(); return; } const detail = event.target.closest('[data-task-detail]'); if (detail) openTaskDetail(detail.dataset.taskDetail, detail.dataset.date); });
$('#managed-task-list').addEventListener('click', (event) => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.edit) { const task = store.getState().tasks.find((item) => item.id === button.dataset.edit); if (!task) return; editingTaskId = task.id; const form = $('#task-form'); form.elements.title.value = task.title; form.elements.description.value = task.description || ''; form.elements.typeId.value = task.typeId || ''; form.elements.date.value = task.startDate; form.elements.recurrence.value = task.recurrence; document.querySelectorAll('#task-weekdays input').forEach((input) => { input.checked = task.weekdays?.includes(Number(input.value)) || false; }); $('#weekday-field').hidden = task.recurrence !== 'weekly'; $('#task-dialog-kicker').textContent = 'EDIT TASK'; $('#task-dialog-title').textContent = '编辑任务'; $('#save-task-button').textContent = '保存修改'; $('#task-dialog').showModal(); return; } if (!button.dataset.delete) return; pendingDeletion = { id: button.dataset.delete, date: button.dataset.date }; $('#delete-dialog').showModal(); });
$('#calendar-grid').addEventListener('click', (event) => { const day = event.target.closest('[data-day]')?.dataset.day; if (day) { state.selectedDate = day; render(); } }); $('#prev-month').onclick = () => { const date = new Date(`${state.month}-01T00:00:00`); date.setMonth(date.getMonth() - 1); state.month = toDateKey(date).slice(0, 7); render(); }; $('#next-month').onclick = () => { const date = new Date(`${state.month}-01T00:00:00`); date.setMonth(date.getMonth() + 1); state.month = toDateKey(date).slice(0, 7); render(); };
$('#member-gate-list').onclick = (event) => { const id = event.target.closest('[data-member-choice]')?.dataset.memberChoice; if (id) chooseMember(id); }; $('#recurrence').onchange = (event) => { $('#weekday-field').hidden = event.target.value !== 'weekly'; };
$('#member-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get('member').trim(); const file = form.get('avatar'); if (file?.size > 1_500_000) { showToast('头像请控制在 1.5MB 以内。'); return; } if (name) { store.addMember(name, await fileToDataUrl(file)); showToast('成员已添加。'); } event.currentTarget.reset(); }); $('#completion-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('completion-image'); if (file?.size > 1_500_000) { showToast('图片请控制在 1.5MB 以内。'); return; } store.completeTask(pendingCompletion.id, pendingCompletion.date, { note: form.get('completion-note').trim(), image: await fileToDataUrl(file) }); $('#completion-dialog').close(); showToast(); }); $('#type-form').addEventListener('submit', (event) => { event.preventDefault(); const name = new FormData(event.currentTarget).get('type').trim(); if (name) { store.addType(name); showToast('任务类型已添加。'); } event.currentTarget.reset(); }); $('#member-list').addEventListener('click', (event) => manageAction(event, 'member')); $('#type-list').addEventListener('click', (event) => manageAction(event, 'type'));
$('#open-manage').onclick = () => openManage(true); $('#open-member-switch').onclick = () => $('#member-switch-dialog').showModal(); $('#member-switch-list').onclick = (event) => { const id = event.target.closest('[data-member-switch]')?.dataset.memberSwitch; if (!id) return; state.memberId = id; $('#member-switch-dialog').close(); render(); }; $('#open-family-password').onclick = () => { familyManagementRequested = true; passwordVerified = false; $('#member-gate').close(); $('#family-password-form').reset(); $('#password-error').hidden = true; $('#family-password-dialog').showModal(); }; $('#family-password-form').addEventListener('submit', (event) => { event.preventDefault(); const password = new FormData(event.currentTarget).get('password'); if (password !== '123456') { $('#password-error').hidden = false; return; } passwordVerified = true; $('#family-password-dialog').close(); $('#member-dialog').showModal(); }); $('#family-password-dialog').addEventListener('close', () => { if (familyManagementRequested && !passwordVerified) $('#member-gate').showModal(); }); $('#member-dialog').addEventListener('close', () => { if (familyManagementRequested) { familyManagementRequested = false; passwordVerified = false; $('#member-gate').showModal(); } }); $('#open-type-dialog').onclick = () => $('#type-dialog').showModal(); $('#open-task-dialog').onclick = () => { editingTaskId = null; const form = $('#task-form'); form.reset(); $('#task-date').value = state.selectedDate; $('#weekday-field').hidden = true; $('#task-dialog-kicker').textContent = 'NEW TASK'; $('#task-dialog-title').textContent = '添加任务'; $('#save-task-button').textContent = '添加到日程'; $('#task-dialog').showModal(); }; document.querySelectorAll('[data-close-dialog]').forEach((button) => { button.onclick = () => $(`#${button.dataset.closeDialog}`).close(); }); $('#delete-future').onclick = () => { store.deleteTask(pendingDeletion.id, 'future', pendingDeletion.date); $('#delete-dialog').close(); showToast('已删除今天及之后的任务。'); }; $('#delete-all').onclick = () => { store.deleteTask(pendingDeletion.id); $('#delete-dialog').close(); showToast('任务已全部删除。'); };
$('#confirm-undo-completion').onclick = () => { store.toggleCompletion(pendingUndoCompletion.id, pendingUndoCompletion.date); $('#undo-completion-dialog').close(); showToast('已撤销完成状态。'); };
$('#completion-form').elements['completion-image'].addEventListener('change', async (event) => { const preview = $('#completion-image-preview'); const file = event.target.files[0]; if (!file) { preview.hidden = true; preview.removeAttribute('src'); return; } if (file.size > 1_500_000) { showToast('图片请控制在 1.5MB 以内。'); event.target.value = ''; preview.hidden = true; return; } preview.src = await fileToDataUrl(file); preview.hidden = false; });
$('#member-form').elements.avatar.addEventListener('change', async (event) => { const preview = $('#member-avatar-add-preview'); const file = event.target.files[0]; if (!file) { preview.hidden = true; return; } if (file.size > 1_500_000) { showToast('头像请控制在 1.5MB 以内。'); event.target.value = ''; preview.hidden = true; return; } preview.src = await fileToDataUrl(file); preview.hidden = false; });
$('#member-avatar-form').addEventListener('submit', async (event) => { event.preventDefault(); const file = new FormData(event.currentTarget).get('member-avatar'); if (!file?.size) { showToast('请选择一张头像。'); return; } if (file.size > 1_500_000) { showToast('头像请控制在 1.5MB 以内。'); return; } store.updateMemberAvatar(editingMemberAvatarId, await fileToDataUrl(file)); $('#member-avatar-dialog').close(); showToast('头像已更新。'); });
$('#member-avatar-form').elements['member-avatar'].addEventListener('change', async (event) => { const preview = $('#member-avatar-preview'); const file = event.target.files[0]; if (!file) return; if (file.size > 1_500_000) { showToast('头像请控制在 1.5MB 以内。'); event.target.value = ''; return; } preview.src = await fileToDataUrl(file); preview.hidden = false; });
$('#open-join-family').onclick = () => { $('#member-gate').close(); $('#join-family-form').reset(); $('#join-family-error').hidden = true; $('#join-family-dialog').showModal(); };
$('#join-family-form').addEventListener('submit', async (event) => { event.preventDefault(); const code = new FormData(event.currentTarget).get('invite-code'); try { await store.joinHousehold(code); $('#join-family-dialog').close(); $('#member-gate').showModal(); render(); showToast('已加入家庭，正在同步任务。'); } catch (error) { $('#join-family-error').textContent = /row-level security/i.test(error.message || '') ? '家庭权限未完成配置，请联系管理员执行最新的邀请迁移。' : (error.message || '邀请码无效，请确认后重试。'); $('#join-family-error').hidden = false; } });
$('#task-date').value = today; store.subscribe(render); render(); setInterval(rotateMotivation, 16000); $('#member-gate').showModal();
store.ready.then(render).catch(() => { $('#family-invite-code').textContent = '需要执行迁移'; showToast('云端同步未连接，当前内容暂存于本机。'); });

function renderIpad() {
  const memberId = state.memberId; const ipad = store.getIpadState(); const limit = ipad.limits.find((item) => item.memberId === memberId && item.date === today); const types = ipad.types.filter((item) => item.memberId === memberId); const entries = ipad.entries.filter((item) => item.memberId === memberId && item.dailyLimitId === limit?.id); const summary = limit ? getDailyUsageSummary(limit, entries, types) : null;
  $('#ipad-limit-options').hidden = Boolean(limit); $('#ipad-summary').hidden = !summary; $('#ipad-summary').textContent = summary ? (summary.isOvertime ? `已超时 ${summary.overtimeMinutes} 分钟` : `剩余 ${summary.remainingMinutes} 分钟`) : ''; $('#ipad-entry-type').innerHTML = types.map((type) => `<option value="${type.id}">${escape(type.name)}${type.countsTowardLimit ? '' : '（不计额度）'}</option>`).join(''); $('#ipad-entry-list').innerHTML = entries.length ? entries.map((entry) => `<div class="manage-row"><strong>${escape(entry.title)}</strong><span>${entry.endedAt ? `${Math.round((new Date(entry.endedAt) - new Date(entry.startedAt)) / 60000)} 分钟` : '计时中'}</span>${entry.endedAt ? '' : `<button class="mini" data-ipad-complete="${entry.id}">完成</button>`}</div>`).join('') : '<div class="empty">还没有使用记录。</div>'; $('#ipad-type-list').innerHTML = types.map((type) => `<div class="manage-row"><strong>${escape(type.name)}</strong><span>${type.countsTowardLimit ? '计入额度' : '不计额度'}</span></div>`).join(''); const dates = ipad.limits.filter((item) => item.memberId === memberId); $('#ipad-calendar-grid').innerHTML = dates.map((item) => { const dayEntries = ipad.entries.filter((entry) => entry.dailyLimitId === item.id); const status = getIpadDayStatus(getDailyUsageSummary(item, dayEntries, ipad.types)); return `<span class="${status}">${item.date.slice(5)} ${status === 'overtime' ? '✕' : '✓'}</span>`; }).join('') || '<span>本月暂无额度记录</span>';
}
$('#open-ipad-manager').onclick = () => { renderIpad(); $('#ipad-manager-dialog').showModal(); };
$('#ipad-limit-options').onclick = (event) => { const minutes = Number(event.target.dataset.ipadLimit); if (!minutes || !state.memberId) return; store.createIpadDailyLimit(state.memberId, today, minutes); renderIpad(); };
$('#open-ipad-entry-dialog').onclick = () => { renderIpad(); $('#ipad-entry-form').reset(); $('#ipad-entry-dialog').showModal(); };
$('#ipad-entry-form').onsubmit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const ipad = store.getIpadState(); const limit = ipad.limits.find((item) => item.memberId === state.memberId && item.date === today); const type = ipad.types.find((item) => item.id === form.get('typeId')); const summary = limit && getDailyUsageSummary(limit, ipad.entries.filter((item) => item.dailyLimitId === limit.id), ipad.types); if (!limit) return; if (summary?.isOvertime && type?.countsTowardLimit && !confirm(`今日已超时 ${summary.overtimeMinutes} 分钟，仍要继续创建吗？`)) return; store.addIpadUsageEntry({ memberId: state.memberId, dailyLimitId: limit.id, typeId: form.get('typeId'), title: form.get('title').trim(), startedAt: new Date().toISOString() }); $('#ipad-entry-dialog').close(); renderIpad(); };
$('#ipad-entry-list').onclick = (event) => { const id = event.target.dataset.ipadComplete; if (id) { store.completeIpadUsageEntry(id, new Date().toISOString()); renderIpad(); } };
$('#open-ipad-type-dialog').onclick = () => { renderIpad(); $('#ipad-type-dialog').showModal(); };
$('#ipad-type-form').onsubmit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get('name').trim(); if (name && state.memberId) store.addIpadUsageType(state.memberId, name, form.get('counts') === 'on'); event.currentTarget.reset(); renderIpad(); };
